openapi: 3.0.0
info:
  title: API Ping
  description: API simple pour vérifier la disponibilité du service
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /ping:
    get:
      summary: Vérifier la disponibilité de l'API
      description: Renvoie un message pong en réponse à un ping
      responses:
        '200':
          description: Réponse réussie
          content:
            text/plain:
              schema:
                type: string
                example: "pong"